name: Build EXE

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Run tests
        run: pytest -q
      - name: Build exe
        run: pyinstaller main.py --onefile --windowed \
          --add-data "Goudstukken.png;." \
          --add-data "Landkaart.png;." \
          --add-data "winkelier.png;." \
          --add-data "assets;assets"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Edu-Dungeon-exe
          path: dist/main.exe
